version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      ignored_updates:
       - match:
          dependency_name: "org.jboss.weld:weld-junit5"
          version_requirement: "2.x"
